import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Bricolage_Grotesque, Anonymous_Pro } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Orbitron } from "next/font/google";
const orbitron = Orbitron({subsets: ['latin']})

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = Anonymous_Pro({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} ${orbitron.className} antialiased`}>{children}</body>
    </html>
  );
}
